### ISSUE TITLE
When aborting (ABORT_USER) via api, the test continues to run

### ISSUE THREAD

**Issue by n8io** [alphatechnologies/trutemp-ui-press#28]
The test status is updated to `ABORT_USER` appropriately, however there are the following issues:
* Test measurements continue to run
* The endDate doesn't update accordingly
* The estimatedEndDate doesn't update accordingly

**Comment by n8io** [comment]
This needs attention @bholtzapple

**Comment by bholtzapple** [comment]
Nate tested and approved the fix
