### ISSUE TITLE
Scrolling is a little spotty 

### ISSUE THREAD

**Issue by bholtzapple** [alphatechnologies/trutemp-ui-press#5]
When I was trying to scroll with my phone it was a little spotty. Not very smooth unless I was on the edge of the screen where there is no element active(ie chart area). This could be just my phone have not tried it on any other mobile device yet.

**Comment by n8io** [comment]
@bholtzapple The scroll touch is getting hung up on the chart because it has a "pinch to zoom" functionality on it. I will remove unless you think it is needed.

**Comment by bholtzapple** [comment]
@n8io. I am ok with that I don't think we will need that granularity.
